\COPY states FROM 'data/states.dat' WITH DELIMITER '|' NULL '' ENCODING 'UTF8'
\COPY persons FROM 'data/persons.dat' WITH DELIMITER '|' NULL '' ENCODING 'UTF8'
\COPY person_roles FROM 'data/person_roles.dat' WITH DELIMITER '|' NULL '' ENCODING 'UTF8'
\COPY votes FROM 'data/votes.dat' WITH DELIMITER '|' NULL '' ENCODING 'UTF8'
\COPY bills FROM 'data/bills.dat' WITH DELIMITER '|' NULL '' ENCODING 'UTF8'
\COPY votes_re_bills FROM 'data/votes_re_bills.dat' WITH DELIMITER '|' NULL ''
\COPY votes_re_amendments FROM 'data/votes_re_amendments.dat' WITH DELIMITER '|' NULL ''
\COPY votes_re_nominations FROM 'data/votes_re_nominations.dat' WITH DELIMITER '|' NULL ''
\COPY person_votes FROM 'data/person_votes.dat' WITH DELIMITER '|' NULL ''
\COPY leadership FROM 'data/leadership.dat' WITH DELIMITER '|' NULL ''
\COPY key_bills FROM 'data/key_bills.dat' WITH DELIMITER '|' NULL ''
\COPY key_votes FROM 'data/key_votes.dat' WITH DELIMITER '|' NULL ''
\COPY bills_subjects FROM 'data/bills_subjects.dat' WITH DELIMITER '|' NULL ''
\COPY presidential_support FROM 'data/pres-support/presidential_support_2012.csv' WITH DELIMITER '|' NULL '' ENCODING 'UTF8'
\COPY presidential_support FROM 'data/pres-support/presidential_support_2013.csv' WITH DELIMITER '|' NULL '' ENCODING 'UTF8'
